sudo: required
dist: trusty
language: node_js
node_js:
  - '7.0.0'
addons:
apt:
  sources:
    - google-chrome
  packages:
    - build-essential
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - eval "$(ssh-agent -s)"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start


script:
- ng build
- karma start karma.conf.js --single-run

after_success:
- echo $TOTO > ssh.txt
- more ssh.txt
- chmod 600 ssh.txt
- ssh-add ssh.txt && ng github-pages:deploy --gh-token $GH_TOKEN
